---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  data_bags_path: ../../chef-config/vault-items

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: bento/oracle-7.3

suites:
  - name: default
    run_list:
      - recipe[segulja_users::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
